name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
  runs-on: windows-latest

  steps:

  - name: Checkout repository
      
     

 
uses: actions/checkout@v2


    

   
- name: Setup Node.js environment
      
      
uses: actions/setup-node@v2
      
  
with:
        
       

 
node-version: '18.18;2'

    

- name: Install dependencies
      
 
run: npm install

    

 
- name: Run tests
      
   
run: npm test
  